name: Lint
on:
    pull_request:
        branches:
            - main
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Source Code"
              uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.12.2
            - name: "Install Dependencies"
              working-directory: ./client
              run: npm install
            - name: "Run linter"
              run: npm run lint
